/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextRevealIndexRouteImport } from './routes/text-reveal/index'
import { Route as ShiningButtonIndexRouteImport } from './routes/shining-button/index'
import { Route as NavbarIndexRouteImport } from './routes/navbar/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRevealIndexRoute = TextRevealIndexRouteImport.update({
  id: '/text-reveal/',
  path: '/text-reveal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiningButtonIndexRoute = ShiningButtonIndexRouteImport.update({
  id: '/shining-button/',
  path: '/shining-button/',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarIndexRoute = NavbarIndexRouteImport.update({
  id: '/navbar/',
  path: '/navbar/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/navbar': typeof NavbarIndexRoute
  '/shining-button': typeof ShiningButtonIndexRoute
  '/text-reveal': typeof TextRevealIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/navbar': typeof NavbarIndexRoute
  '/shining-button': typeof ShiningButtonIndexRoute
  '/text-reveal': typeof TextRevealIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/navbar/': typeof NavbarIndexRoute
  '/shining-button/': typeof ShiningButtonIndexRoute
  '/text-reveal/': typeof TextRevealIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/navbar' | '/shining-button' | '/text-reveal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/navbar' | '/shining-button' | '/text-reveal'
  id: '__root__' | '/' | '/navbar/' | '/shining-button/' | '/text-reveal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NavbarIndexRoute: typeof NavbarIndexRoute
  ShiningButtonIndexRoute: typeof ShiningButtonIndexRoute
  TextRevealIndexRoute: typeof TextRevealIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-reveal/': {
      id: '/text-reveal/'
      path: '/text-reveal'
      fullPath: '/text-reveal'
      preLoaderRoute: typeof TextRevealIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shining-button/': {
      id: '/shining-button/'
      path: '/shining-button'
      fullPath: '/shining-button'
      preLoaderRoute: typeof ShiningButtonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navbar/': {
      id: '/navbar/'
      path: '/navbar'
      fullPath: '/navbar'
      preLoaderRoute: typeof NavbarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NavbarIndexRoute: NavbarIndexRoute,
  ShiningButtonIndexRoute: ShiningButtonIndexRoute,
  TextRevealIndexRoute: TextRevealIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
