/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DepartureBoardRouteImport } from './routes/departure-board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextRevealIndexRouteImport } from './routes/text-reveal/index'
import { Route as NavbarIndexRouteImport } from './routes/navbar/index'

const DepartureBoardRoute = DepartureBoardRouteImport.update({
  id: '/departure-board',
  path: '/departure-board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRevealIndexRoute = TextRevealIndexRouteImport.update({
  id: '/text-reveal/',
  path: '/text-reveal/',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarIndexRoute = NavbarIndexRouteImport.update({
  id: '/navbar/',
  path: '/navbar/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/departure-board': typeof DepartureBoardRoute
  '/navbar': typeof NavbarIndexRoute
  '/text-reveal': typeof TextRevealIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/departure-board': typeof DepartureBoardRoute
  '/navbar': typeof NavbarIndexRoute
  '/text-reveal': typeof TextRevealIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/departure-board': typeof DepartureBoardRoute
  '/navbar/': typeof NavbarIndexRoute
  '/text-reveal/': typeof TextRevealIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/departure-board' | '/navbar' | '/text-reveal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/departure-board' | '/navbar' | '/text-reveal'
  id: '__root__' | '/' | '/departure-board' | '/navbar/' | '/text-reveal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepartureBoardRoute: typeof DepartureBoardRoute
  NavbarIndexRoute: typeof NavbarIndexRoute
  TextRevealIndexRoute: typeof TextRevealIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/departure-board': {
      id: '/departure-board'
      path: '/departure-board'
      fullPath: '/departure-board'
      preLoaderRoute: typeof DepartureBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-reveal/': {
      id: '/text-reveal/'
      path: '/text-reveal'
      fullPath: '/text-reveal'
      preLoaderRoute: typeof TextRevealIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navbar/': {
      id: '/navbar/'
      path: '/navbar'
      fullPath: '/navbar'
      preLoaderRoute: typeof NavbarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepartureBoardRoute: DepartureBoardRoute,
  NavbarIndexRoute: NavbarIndexRoute,
  TextRevealIndexRoute: TextRevealIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
